DECLARE VARIABLE var_period STRING DEFAULT '202507';
DECLARE VARIABLE var_version STRING DEFAULT 'public.F05';
DECLARE VARIABLE var_actual STRING DEFAULT 'public.Actual';

WITH SAC AS (
SELECT
  LPAD(CUSTOMER,10,'0') AS SAC_CUSTOMER,
  CONCAT(LEFT(LPAD(PRODUCT,18,'0'),17,'0') AS SAC_PRODUCT,
  Version,
  Date,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_Volume' THEN QTY_CS
      ELSE 0
      END) AS SHIPPED_CS,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_GrossSalesOutside' THEN AMOUNT_LC
      ELSE 0
      END) AS GROSS_SALES,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_Billbacks' THEN AMOUNT_LC
      WHEN 'PBI_OffInvoice' THEN AMOUNT_LC
      WHEN 'PBI_CustMerch' THEN AMOUNT_LC
      WHEN 'PBI_FixedTrade' THEN AMOUNT_LC
      ELSE 0
    END) AS TRADE_SPEND,
  SUM(AMOUNT_LC) as AMOUNT_LC
FROM uc_prod.dw_s_sac.s_sac_am_sac_pln_fst sac
WHERE 
  1=1
  AND sac.Version IN (var_version,'public.AOP',var_actual) --'public.F05'
  AND sac.COMP_CODE = 'US12'
  AND sac.DATA_SRC IN ('POST_ALLOC','S4_ACTUAL','S4_TPM_ACCRUALS','GR Outages')
  AND sac.CUSTOMER <> "#"
  AND LEFT(Date,4) = '2025'

GROUP BY ALL

ORDER BY Date 
)
,

SAC_PRICING_BOY AS (
    SELECT 
    dim_cust.CUSTOMERNAME1,
    dim_cust.CUSTOMERNAME2,
    dim_cust.CUSTOMERNAME3,
    dim_cust.CUSTOMERNAME4,
    dim_cust.CUSTOMERNAME5,
    dim_prod.PRODUCTHIERARCHY_L1_TEXT,
    dim_prod.PRODUCTHIERARCHY_L2_TEXT,
    dim_prod.PRODUCTHIERARCHY_L3_TEXT,
    dim_prod.PRODUCTHIERARCHY_L4_TEXT,
    dim_prod.PRODUCTHIERARCHY_L5_TEXT,
    concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as SubBrandVolumeSize,
    SAC.Version,
    SUM(GROSS_SALES)/SUM(SHIPPED_CS) AS LIST_PRICE_BOY5


    FROM SAC
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
        ON dim_cust.CUSTOMER = SAC.SAC_CUSTOMER
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
    ON SAC.SAC_PRODUCT = dim_prod.PRODUCT

    WHERE 
    1=1
        AND Date >= var_period
        AND SAC.Version =  var_version

        GROUP BY ALL
        ORDER BY SubBrandVolumeSize, CUSTOMERNAME2, CUSTOMERNAME3,CUSTOMERNAME4,CUSTOMERNAME5
),

SAC_PRICING_BOY4 AS (
    SELECT 
    dim_cust.CUSTOMERNAME1,
    dim_cust.CUSTOMERNAME2,
    dim_cust.CUSTOMERNAME3,
    dim_cust.CUSTOMERNAME4,
    dim_prod.PRODUCTHIERARCHY_L1_TEXT,
    dim_prod.PRODUCTHIERARCHY_L2_TEXT,
    dim_prod.PRODUCTHIERARCHY_L3_TEXT,
    dim_prod.PRODUCTHIERARCHY_L4_TEXT,
    dim_prod.PRODUCTHIERARCHY_L5_TEXT,
    concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as SubBrandVolumeSize,
    SAC.Version,
    SUM(GROSS_SALES)/SUM(SHIPPED_CS) AS LIST_PRICE_BOY4


    FROM SAC
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
        ON dim_cust.CUSTOMER = SAC.SAC_CUSTOMER
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
    ON SAC.SAC_PRODUCT = dim_prod.PRODUCT

    WHERE 
    1=1
        AND Date >= var_period
        AND SAC.Version = var_version
        GROUP BY ALL
        ORDER BY SubBrandVolumeSize, CUSTOMERNAME2, CUSTOMERNAME3,CUSTOMERNAME4
),
IBP6 AS
    (
        SELECT 
            -- *
            ibp.PERIOD_ID,
            CONCAT('20',SUBSTRING(ibp.PERIOD_ID,5,2),RIGHT(ibp.PERIOD_ID,2)) as IBP_CALWEEK,
            SUM(ibp.CONSENSUSDEMANDQTY) as IBP_DEMAND_PLAN,
            ibp_prod.TBGPRODHL1DESC,
            ibp_prod.TBGPRODHL2DESC,
            ibp_prod.TBGPRODHL3DESC,
            ibp_prod.TBGPRODHL4DESC,
            ibp_prod.TBGPRODHL5DESC,
            concat(ibp_prod.TBGPRODHL3DESC," ",ibp_prod.TBGPRODHL5DESC) as IBP_SubBrandVolumeSize,
            CONCAT(LEFT(LPAD(PROD_ID,18,'0'),17),'0') AS IBP_MATERIAL,
            dim_cust.CUSTOMERNAME1,
            dim_cust.CUSTOMERNAME2,
            dim_cust.CUSTOMERNAME3,
            dim_cust.CUSTOMERNAME4,
            dim_cust.CUSTOMERNAME5,
            dim_cust.CUSTOMERNAME6
            FROM uc_prod.dw_s_ibp.s_am_ibp_shipments_forecast_uc ibp
            LEFT JOIN uc_prod.dw_s_ibp.s_cv_dim_ibp_prdid ibp_prod
            ON ibp.PROD_ID = ibp_prod.PRDID 
            LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
            ON dim_cust.CUSTOMER = ibp.CUST_ID

            WHERE 
            1=1
            AND dim_cust.SALES_ORGANIZATION = 'US12'
            AND ibp.PERIOD_ID LIKE "%25-%"            

            GROUP BY ALL
    ),

IBP5 AS
    (
        SELECT 
            -- *
            ibp.PERIOD_ID,
            CONCAT('20',SUBSTRING(ibp.PERIOD_ID,5,2),RIGHT(ibp.PERIOD_ID,2)) as IBP_CALWEEK,
            SUM(ibp.CONSENSUSDEMANDQTY) as IBP_DEMAND_PLAN,
            ibp_prod.TBGPRODHL1DESC,
            ibp_prod.TBGPRODHL2DESC,
            ibp_prod.TBGPRODHL3DESC,
            ibp_prod.TBGPRODHL4DESC,
            ibp_prod.TBGPRODHL5DESC,
            concat(ibp_prod.TBGPRODHL3DESC," ",ibp_prod.TBGPRODHL5DESC) as IBP_SubBrandVolumeSize,
            CONCAT(LEFT(LPAD(PROD_ID,18,'0'),17),'0') AS IBP_MATERIAL,
            dim_cust.CUSTOMERNAME1,
            dim_cust.CUSTOMERNAME2,
            dim_cust.CUSTOMERNAME3,
            dim_cust.CUSTOMERNAME4,
            dim_cust.CUSTOMERNAME5
            FROM uc_prod.dw_s_ibp.s_am_ibp_shipments_forecast_uc ibp
            LEFT JOIN uc_prod.dw_s_ibp.s_cv_dim_ibp_prdid ibp_prod
            ON ibp.PROD_ID = ibp_prod.PRDID 
            LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
            ON dim_cust.CUSTOMER = ibp.CUST_ID

            WHERE 
            1=1
            AND dim_cust.SALES_ORGANIZATION = 'US12'
            AND ibp.PERIOD_ID LIKE "%25-%"
            
            GROUP BY ALL
    )
,
dim_cust AS(
  SELECT 
  DISTINCT
  CUSTOMERNAME1,
  CUSTOMERNAME2,
  CUSTOMERNAME3,
  CUSTOMERNAME4,
  CUSTOMERNAME5,
  HKUNNR5
  FROM uc_prod.dw_s_md.s_mdm_cv_dim_customer
),
tpm AS(
  SELECT
    *,
    CONCAT(LEFT(LPAD(MATERIAL,18,'0'),17),'0') AS SAP_MATERIAL,
    CASE
      WHEN F_SPDTDESC = 'OI %' THEN BIC_ATP_OI
      WHEN F_SPDTDESC = 'BB Direct %' THEN BIC_ATP_BB
      WHEN F_SPDTDESC = 'BB Indirect %' THEN BIC_ATP_BBIN
      WHEN F_SPDTDESC = 'Scan %' THEN BIC_ATT_SCAN
      WHEN F_SPDTDESC = 'Depletion %' THEN BIC_ATP_DPN
    END AS ALLOWANCE_PCT,
    CASE
      WHEN F_SPDTDESC = 'OI Rate/Case' THEN BIC_ATT_OI
      WHEN F_SPDTDESC = 'BB Direct Rate/Case' THEN BIC_ATT_BB
      WHEN F_SPDTDESC = 'BB Ind. Rate/Case' THEN BIC_ATT_BBIN
      WHEN F_SPDTDESC = 'Scan Rate/Case' THEN BIC_ATC_SCAN
      WHEN F_SPDTDESC = 'Depletion Rate/Case' THEN BIC_ATT_DPN
    END AS ALLOWANCE_CASE,    
    CASE
      WHEN F_SPDTDESC = 'BB Direct %' THEN BIC_ATA_BBP
      WHEN F_SPDTDESC = 'BB Direct Rate/Case' THEN BIC_ATA_BBC
      WHEN F_SPDTDESC = 'BB Indirect %' THEN BIC_ATA_BB_0 -- + BIC_ATA_BBIN
      WHEN F_SPDTDESC = 'BB Ind. Rate/Case' THEN BIC_ATA_BBIN -- CONFIRM second option BIC_ATL_EDLP
      WHEN F_SPDTDESC = 'Coupon Fixed' THEN BIC_ATL_CPN --CONFIRM
      WHEN F_SPDTDESC = 'Depletion %' THEN BIC_ATA_DPNP
      WHEN F_SPDTDESC = 'Depletion Rate/Case' THEN BIC_ATA_DPNC
      WHEN F_SPDTDESC = 'Display Fixed' THEN BIC_ATL_DSP  --CONFIRM
      WHEN F_SPDTDESC = 'Feature Fixed' THEN BIC_ATL_FTR2 --CONFIRM BIC_ATL_FTR is for Lump Sum
      WHEN F_SPDTDESC = 'Fixed' THEN BIC_ATL_SHLF --CONFIRM
      WHEN F_SPDTDESC = 'OI %' THEN BIC_ATA_OIP
      WHEN F_SPDTDESC = 'OI Rate/Case' THEN BIC_ATA_OIC
      WHEN F_SPDTDESC = 'Scan %' THEN BIC_ATA_SCNP
      WHEN F_SPDTDESC = 'Scan Rate/Case' THEN BIC_ATA_SCNC
      WHEN F_SPDTDESC = 'Slotting Fixed' THEN BIC_ATL_SLT  --CONFIRM
    END AS FORECAST_TRADE_SPEND
  FROM uc_prod.dw_s_tpm.s_tbg_am_tpm_tmacpr012
  WHERE 1=1
  AND SALESORG = 'US12'
  AND CALYEAR = '2025'

)

,

TPM_AGG AS (
SELECT 
tpm.SAP_MATERIAL,
tpm.CRM_MKTELM as T_CODE,
CALWEEK,
FISCPER_NO,
CALYEAR,
F_SPDTDESC as SPEND_TYPE,
OBJECTIVE_DE as TERM,
`/BIC/APRMSTD` AS STATUS,
MAX(BIC_ANT_LSTP) as LIST_PRICE,
MAX(ALLOWANCE_PCT) as ALLOWANCE_PCT,
MAX(ALLOWANCE_CASE) as ALLOWANCE_CASE,
SUM(`/BIC/AVT_SCAN`) as SCAN_VOLUME,
SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
SUM(`/BIC/APA_TGSSH`) as FORECAST_GROSS_DOLLARS,
SUM(`/BIC/AVT_BASSH`) as FORECAST_TOTAL_SHIPMENT_VOLUME,
MAX(`/BIC/APA_TOTRD`) AS T_CODE_TRADE_SPEND,
dim_cust.CUSTOMERNAME1,
dim_cust.CUSTOMERNAME2,
dim_cust.CUSTOMERNAME3,
dim_cust.CUSTOMERNAME4,
dim_cust.CUSTOMERNAME5,
tpm.L6_CUST_TEXT,
dim_prod.PRODUCTHIERARCHY_L1_TEXT,
dim_prod.PRODUCTHIERARCHY_L2_TEXT,
dim_prod.PRODUCTHIERARCHY_L3_TEXT,
dim_prod.PRODUCTHIERARCHY_L4_TEXT,
dim_prod.PRODUCTHIERARCHY_L5_TEXT,
concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as TPM_SubBrandVolumeSize
FROM tpm
LEFT JOIN dim_cust
ON tpm.CUST_SALES = dim_cust.HKUNNR5
LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
ON tpm.SAP_MATERIAL = dim_prod.PRODUCT
WHERE
1=1
AND tpm.CRM_MKTELM != " "

GROUP BY ALL

)


,


IBP2TPM AS(
SELECT 
TPM_AGG.T_CODE,
TPM_AGG.STATUS,
COALESCE(TPM_AGG.CALWEEK,IBP6.IBP_CALWEEK,IBP5.IBP_CALWEEK) as CALWEEK,
TPM_AGG.FISCPER_NO,
COALESCE(LEFT(TPM_AGG.CALWEEK,4),LEFT(IBP6.IBP_CALWEEK,4),LEFT(IBP5.IBP_CALWEEK,4)) AS CALYEAR,
TPM_AGG.SPEND_TYPE,
TPM_AGG.TERM,
TPM_AGG.LIST_PRICE,
TPM_AGG.ALLOWANCE_PCT,
TPM_AGG.ALLOWANCE_CASE,
TPM_AGG.SCAN_VOLUME,
TPM_AGG.FORECAST_TRADE_SPEND,
TPM_AGG.FORECAST_GROSS_DOLLARS,
TPM_AGG.FORECAST_TOTAL_SHIPMENT_VOLUME,
TPM_AGG.T_CODE_TRADE_SPEND,
COALESCE(TPM_AGG.CUSTOMERNAME1,IBP6.CUSTOMERNAME1,IBP5.CUSTOMERNAME1) as CUSTOMERNAME1, 
COALESCE(TPM_AGG.CUSTOMERNAME2,IBP6.CUSTOMERNAME2,IBP5.CUSTOMERNAME2) as CUSTOMERNAME2,
COALESCE(TPM_AGG.CUSTOMERNAME3,IBP6.CUSTOMERNAME3,IBP5.CUSTOMERNAME3) as CUSTOMERNAME3,
COALESCE(TPM_AGG.CUSTOMERNAME4,IBP6.CUSTOMERNAME4,IBP5.CUSTOMERNAME4) as CUSTOMERNAME4,
COALESCE(TPM_AGG.CUSTOMERNAME5,IBP6.CUSTOMERNAME5,IBP5.CUSTOMERNAME5) as CUSTOMERNAME5,
COALESCE(TPM_AGG.L6_CUST_TEXT,IBP6.CUSTOMERNAME6) as CUSTOMERNAME6,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L1_TEXT,IBP6.TBGPRODHL1DESC,IBP5.TBGPRODHL1DESC) as PRODUCTHIERARCHY_L1_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L2_TEXT,IBP6.TBGPRODHL2DESC,IBP5.TBGPRODHL2DESC) as PRODUCTHIERARCHY_L2_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L3_TEXT,IBP6.TBGPRODHL3DESC,IBP5.TBGPRODHL3DESC) as PRODUCTHIERARCHY_L3_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L4_TEXT,IBP6.TBGPRODHL4DESC,IBP5.TBGPRODHL4DESC) as PRODUCTHIERARCHY_L4_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L5_TEXT,IBP6.TBGPRODHL5DESC,IBP5.TBGPRODHL5DESC) as PRODUCTHIERARCHY_L5_TEXT,
COALESCE(TPM_AGG.TPM_SubBrandVolumeSize,IBP6.IBP_SubBrandVolumeSize,IBP5.IBP_SubBrandVolumeSize) as SubBrandVolumeSize,
COALESCE(TPM_AGG.SAP_MATERIAL,IBP6.IBP_MATERIAL,IBP5.IBP_MATERIAL) AS MATERIAL,
IBP6.IBP_DEMAND_PLAN AS IBP_DEMAND_PLAN_L6,
IBP5.IBP_DEMAND_PLAN,
CASE
    WHEN COALESCE(IBP6.IBP_DEMAND_PLAN,IBP5.IBP_DEMAND_PLAN) <=0 THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN COALESCE(IBP6.IBP_DEMAND_PLAN,IBP5.IBP_DEMAND_PLAN) IS NULL THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN RIGHT(TPM_AGG.SPEND_TYPE,5) = 'Fixed' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SCAN_VOLUME > IBP6.IBP_DEMAND_PLAN AND LEFT(TPM_AGG.SPEND_TYPE,4)='Scan' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct %','Depletion %','OI %','Scan %') THEN TPM_AGG.ALLOWANCE_PCT*TPM_AGG.LIST_PRICE*IBP6.IBP_DEMAND_PLAN/100
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct Rate/Case','Depletion Rate/Case','OI Rate/Case','Scan Rate/Case') THEN TPM_AGG.ALLOWANCE_CASE*IBP6.IBP_DEMAND_PLAN

    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SCAN_VOLUME > IBP5.IBP_DEMAND_PLAN AND LEFT(TPM_AGG.SPEND_TYPE,4)='Scan' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct %','Depletion %','OI %','Scan %') THEN TPM_AGG.ALLOWANCE_PCT*TPM_AGG.LIST_PRICE*IBP5.IBP_DEMAND_PLAN/100
    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct Rate/Case','Depletion Rate/Case','OI Rate/Case','Scan Rate/Case') THEN TPM_AGG.ALLOWANCE_CASE*IBP5.IBP_DEMAND_PLAN

END AS CALCULATED_TRADE_SPEND
FROM TPM_AGG
FULL OUTER JOIN IBP6
ON 
    TPM_AGG.SAP_MATERIAL = IBP6.IBP_MATERIAL
    AND TPM_AGG.L6_CUST_TEXT = IBP6.CUSTOMERNAME6
    AND TPM_AGG.CALWEEK = IBP6.IBP_CALWEEK

FULL OUTER JOIN IBP5
ON 
    TPM_AGG.SAP_MATERIAL = IBP5.IBP_MATERIAL
    AND TPM_AGG.CUSTOMERNAME5 = IBP5.CUSTOMERNAME5
    AND TPM_AGG.CALWEEK = IBP5.IBP_CALWEEK

ORDER BY TPM_AGG.CUSTOMERNAME5, TPM_AGG.T_CODE, TPM_AGG.TPM_SubBrandVolumeSize, TPM_AGG.SPEND_TYPE, TPM_AGG.CALWEEK
)

SELECT * FROM IBP2TPM
WHERE FISCPER_NO in ('8','9','10')
