-- SELECT DISTINCT Version, Data_SRC FROM uc_prod.dw_s_sac.s_sac_am_sac_pln_fst ORDER BY 1,2
DECLARE VARIABLE var_period STRING DEFAULT '202507';
DECLARE VARIABLE var_version STRING DEFAULT 'public.F05';
DECLARE VARIABLE var_actual STRING DEFAULT 'public.Actual';
-- DECLARE VARIABLE var_pricingperiod STRING DEFAULT '202505';
-- SELECT * FROM uc_prod.dw_s_sac.s_sac_am_sac_pln_fst LIMIT 500
WITH SAC AS (
SELECT
  LPAD(CUSTOMER,10,'0') AS SAC_CUSTOMER,
  LPAD(PRODUCT,18,'0') AS SAC_PRODUCT,
  Version,
  -- DATA_SRC,
  Date,
  -- ACCOUNT_PnL,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_Volume' THEN QTY_CS
      ELSE 0
      END) AS SHIPPED_CS,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_GrossSalesOutside' THEN AMOUNT_LC
      ELSE 0
      END) AS GROSS_SALES,
  SUM(
    CASE ACCOUNT_PnL
      WHEN 'PBI_Billbacks' THEN AMOUNT_LC
      WHEN 'PBI_OffInvoice' THEN AMOUNT_LC
      WHEN 'PBI_CustMerch' THEN AMOUNT_LC
      WHEN 'PBI_FixedTrade' THEN AMOUNT_LC
      ELSE 0
    END) AS TRADE_SPEND,
  SUM(AMOUNT_LC) as AMOUNT_LC
FROM uc_prod.dw_s_sac.s_sac_am_sac_pln_fst sac
WHERE 
  1=1
  AND sac.Version IN (var_version,'public.AOP',var_actual) --'public.F05'
  AND sac.COMP_CODE = 'US12'
  AND sac.DATA_SRC IN ('POST_ALLOC','S4_ACTUAL','S4_TPM_ACCRUALS','GR Outages')
  AND sac.CUSTOMER <> "#"
  AND LEFT(Date,4) = '2025'
  -- AND sac.Date <= var_period

GROUP BY ALL

ORDER BY Date 
)
-- SELECT Version,Date, SUM(SHIPPED_CS),SUM(GROSS_SALES),SUM(TRADE_SPEND) FROM SAC GROUP BY ALL ORDER BY 1,2
-- SELECT SUM(SHIPPED_CS) FROM SAC
,
--49,882,729.73

-- SAC_DIM1 AS (
--     SELECT 
--     dim_cust.CUSTOMERNAME1,
--     dim_cust.CUSTOMERNAME2,
--     dim_cust.CUSTOMERNAME3,
--     dim_cust.CUSTOMERNAME4,
--     dim_cust.CUSTOMERNAME5,
--     -- dim_cust.CUSTOMERNAME6,
--     dim_prod.PRODUCTHIERARCHY_L1_TEXT,
--     dim_prod.PRODUCTHIERARCHY_L2_TEXT,
--     dim_prod.PRODUCTHIERARCHY_L3_TEXT,
--     dim_prod.PRODUCTHIERARCHY_L4_TEXT,
--     dim_prod.PRODUCTHIERARCHY_L5_TEXT,
--     concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as SubBrandVolumeSize,
--     CASE
--         WHEN SAC.Version = 'public.AOP' THEN SUM(SHIPPED_CS)
--     END AS SHIPPED_CS_AOP,
--     CASE
--         WHEN SAC.Date >= var_period AND SAC.Version = var_version THEN SUM(SHIPPED_CS)
--         WHEN SAC.Date < var_period AND SAC.Version = var_actual THEN SUM(SHIPPED_CS)
--     END AS SHIPPED_CS_SAC,

--     CASE
--         WHEN SAC.Version = 'public.AOP' THEN SUM(GROSS_SALES)
--     END AS GROSS_SALES_AOP,
--     CASE
--         WHEN SAC.Date >= var_period AND SAC.Version = var_version THEN SUM(GROSS_SALES)
--         WHEN SAC.Date < var_period AND SAC.Version = var_actual THEN SUM(GROSS_SALES)
--     END AS GROSS_SALES_SAC,

--     CASE
--         WHEN SAC.Version = 'public.AOP' THEN SUM(TRADE_SPEND)
--     END AS TRADE_SPEND_AOP,
--     CASE
--         WHEN SAC.Date >= var_period AND SAC.Version = var_version THEN SUM(TRADE_SPEND)
--         WHEN SAC.Date < var_period AND SAC.Version = var_actual THEN SUM(TRADE_SPEND)
--     END AS TRADE_SPEND_SAC,
--     SAC.Version,
--     -- SAC.DATA_SRC,
--     SAC.Date
--     -- SAC.ACCOUNT_PnL,
--     -- SUM(SHIPPED_CS) AS SHIPPED_CS_SAC,
--     -- SUM(GROSS_SALES) AS GROSS_SALES_SAC,
--     -- SUM(TRADE_SPEND) AS TRADE_SPEND_SAC
--     -- SUM(TRADE_SPEND)/SUM(GROSS_SALES) AS T2S_YTD
--     FROM SAC
--     LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
--         ON dim_cust.CUSTOMER = SAC.SAC_CUSTOMER
--     LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
--     ON SAC.SAC_PRODUCT = dim_prod.PRODUCT

--     WHERE 
--     1=1
--     -- AND dim_cust.CUSTOMERNAME5 = 'KROGER CO.'
--     -- AND Date <= var_period
--     GROUP BY ALL
-- )
-- -- SELECT 
-- --     Date,
-- --     Version,
-- --     SUM(SHIPPED_CS_AOP),
-- --     SUM(SHIPPED_CS_SAC),
-- --     SUM(GROSS_SALES_AOP),
-- --     SUM(GROSS_SALES_SAC),
-- --     SUM(TRADE_SPEND_AOP),
-- --     SUM(TRADE_SPEND_SAC)
-- -- FROM SAC_DIM1
-- -- GROUP BY ALL
-- -- ORDER BY 1,2
-- ,
-- SAC_DIM AS (
--     SELECT 
--     CUSTOMERNAME1,
--     CUSTOMERNAME2,
--     CUSTOMERNAME3,
--     CUSTOMERNAME4,
--     CUSTOMERNAME5,
--     -- CUSTOMERNAME6,
--     PRODUCTHIERARCHY_L1_TEXT,
--     PRODUCTHIERARCHY_L2_TEXT,
--     PRODUCTHIERARCHY_L3_TEXT,
--     PRODUCTHIERARCHY_L4_TEXT,
--     PRODUCTHIERARCHY_L5_TEXT,
--     SubBrandVolumeSize,
--     SUM(SHIPPED_CS_AOP) AS SHIPPED_CS_AOP,
--     SUM(SHIPPED_CS_SAC) AS SHIPPED_CS_SAC,
--     SUM(GROSS_SALES_AOP) AS GROSS_SALES_AOP,
--     SUM(GROSS_SALES_SAC) AS GROSS_SALES_SAC,
--     SUM(TRADE_SPEND_AOP) AS TRADE_SPEND_AOP,
--     SUM(TRADE_SPEND_SAC) AS TRADE_SPEND_SAC,
--     -- SAC.Version,
--     -- SAC.DATA_SRC,
--     Date
--     -- SAC.ACCOUNT_PnL,
--     -- SUM(SHIPPED_CS) AS SHIPPED_CS_SAC,
--     -- SUM(GROSS_SALES) AS GROSS_SALES_SAC,
--     -- SUM(TRADE_SPEND) AS TRADE_SPEND_SAC
--     -- SUM(TRADE_SPEND)/SUM(GROSS_SALES) AS T2S_YTD
--     FROM SAC_DIM1

--     GROUP BY ALL

-- )
-- -- SELECT 
-- --     Date,
-- --     SUM(SHIPPED_CS_AOP),
-- --     SUM(SHIPPED_CS_SAC),
-- --     SUM(GROSS_SALES_AOP),
-- --     SUM(GROSS_SALES_SAC),
-- --     SUM(TRADE_SPEND_AOP),
-- --     SUM(TRADE_SPEND_SAC)
-- -- FROM SAC_DIM
-- -- GROUP BY ALL
-- -- ORDER BY 1
-- -- SELECT * FROM SAC_DIM
-- -- SELECT SUM(SHIPPED_CS_SAC) FROM SAC_DIM
-- --127,215,977.74
-- --103,836,503.35
-- ,

SAC_PRICING_BOY AS (
    SELECT 
    dim_cust.CUSTOMERNAME1,
    dim_cust.CUSTOMERNAME2,
    dim_cust.CUSTOMERNAME3,
    dim_cust.CUSTOMERNAME4,
    dim_cust.CUSTOMERNAME5,
    dim_prod.PRODUCTHIERARCHY_L1_TEXT,
    dim_prod.PRODUCTHIERARCHY_L2_TEXT,
    dim_prod.PRODUCTHIERARCHY_L3_TEXT,
    dim_prod.PRODUCTHIERARCHY_L4_TEXT,
    dim_prod.PRODUCTHIERARCHY_L5_TEXT,
    concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as SubBrandVolumeSize,
    SAC.Version,
    -- SAC.DATA_SRC,
    -- SAC.Date,
    -- SAC.ACCOUNT_PnL,
    SUM(GROSS_SALES)/SUM(SHIPPED_CS) AS LIST_PRICE_BOY5


    FROM SAC
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
        ON dim_cust.CUSTOMER = SAC.SAC_CUSTOMER
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
    ON SAC.SAC_PRODUCT = dim_prod.PRODUCT

    WHERE 
    1=1
    -- AND dim_cust.CUSTOMERNAME5 = 'KROGER CO.'
        AND Date >= var_period
        -- AND Date <= var_pricingperiod
        AND SAC.Version =  var_version

        GROUP BY ALL
        ORDER BY SubBrandVolumeSize, CUSTOMERNAME2, CUSTOMERNAME3,CUSTOMERNAME4,CUSTOMERNAME5
)
-- SELECT * FROM SAC_PRICING_BOY LIMIT 500
,
SAC_PRICING_BOY4 AS (
    SELECT 
    dim_cust.CUSTOMERNAME1,
    dim_cust.CUSTOMERNAME2,
    dim_cust.CUSTOMERNAME3,
    dim_cust.CUSTOMERNAME4,
    -- dim_cust.CUSTOMERNAME5,
    dim_prod.PRODUCTHIERARCHY_L1_TEXT,
    dim_prod.PRODUCTHIERARCHY_L2_TEXT,
    dim_prod.PRODUCTHIERARCHY_L3_TEXT,
    dim_prod.PRODUCTHIERARCHY_L4_TEXT,
    dim_prod.PRODUCTHIERARCHY_L5_TEXT,
    concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as SubBrandVolumeSize,
    SAC.Version,
    -- SAC.DATA_SRC,
    -- SAC.Date,
    -- SAC.ACCOUNT_PnL,
    SUM(GROSS_SALES)/SUM(SHIPPED_CS) AS LIST_PRICE_BOY4


    FROM SAC
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
        ON dim_cust.CUSTOMER = SAC.SAC_CUSTOMER
    LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
    ON SAC.SAC_PRODUCT = dim_prod.PRODUCT

    WHERE 
    1=1
    -- AND dim_cust.CUSTOMERNAME5 = 'KROGER CO.'
        AND Date >= var_period
        -- AND Date <= var_pricingperiod
        AND SAC.Version = var_version
        GROUP BY ALL
        ORDER BY SubBrandVolumeSize, CUSTOMERNAME2, CUSTOMERNAME3,CUSTOMERNAME4
),
IBP6 AS
    (
        SELECT 
            -- *
            ibp.PERIOD_ID,
            CONCAT('20',SUBSTRING(ibp.PERIOD_ID,5,2),RIGHT(ibp.PERIOD_ID,2)) as IBP_CALWEEK,
            SUM(ibp.CONSENSUSDEMANDQTY) as IBP_DEMAND_PLAN,
            ibp_prod.TBGPRODHL1DESC,
            ibp_prod.TBGPRODHL2DESC,
            ibp_prod.TBGPRODHL3DESC,
            ibp_prod.TBGPRODHL4DESC,
            ibp_prod.TBGPRODHL5DESC,
            concat(ibp_prod.TBGPRODHL3DESC," ",ibp_prod.TBGPRODHL5DESC) as IBP_SubBrandVolumeSize,
            LPAD(PROD_ID,18,'0') AS IBP_MATERIAL,
            dim_cust.CUSTOMERNAME1,
            dim_cust.CUSTOMERNAME2,
            dim_cust.CUSTOMERNAME3,
            dim_cust.CUSTOMERNAME4,
            dim_cust.CUSTOMERNAME5,
            dim_cust.CUSTOMERNAME6
            FROM uc_prod.dw_s_ibp.s_am_ibp_shipments_forecast_uc ibp
            LEFT JOIN uc_prod.dw_s_ibp.s_cv_dim_ibp_prdid ibp_prod
            ON ibp.PROD_ID = ibp_prod.PRDID 
            LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
            ON dim_cust.CUSTOMER = ibp.CUST_ID

            WHERE 
            1=1
            AND dim_cust.SALES_ORGANIZATION = 'US12'
            AND ibp.PERIOD_ID LIKE "%25-%"
            -- TESTING
            -- AND dim_cust.CUSTOMERNAME5 = 'WAKEFERN FOODS'
            -- AND ibp_prod.TBGPRODHL3DESC = 'KEVITA SPD'
            -- AND dim_cust.CUSTOMERNAME1 = 'NORTH AMERICA'
            -- AND dim_cust.CUSTOMERNAME2 <> 'CANADA'


            GROUP BY ALL
    ),

-- SELECT DISTINCT CUSTOMERNAME5, CUSTOMERNAME6 FROM IBP WHERE CUSTOMERNAME4 IN ('METRO NY - DSD','METRO NY - IO SERVICED','VIRTUAL SALES') ORDER BY 1,2
-- SELECT * FROM IBP WHERE CUSTOMERNAME5 = 'DAIRIES' and IBP_SubBrandVolumeSize LIKE "%NAKED JUICE SMOOTHIE%" AND IBP_CALWEEK = '202524' 



IBP5 AS
    (
        SELECT 
            -- *
            ibp.PERIOD_ID,
            CONCAT('20',SUBSTRING(ibp.PERIOD_ID,5,2),RIGHT(ibp.PERIOD_ID,2)) as IBP_CALWEEK,
            SUM(ibp.CONSENSUSDEMANDQTY) as IBP_DEMAND_PLAN,
            ibp_prod.TBGPRODHL1DESC,
            ibp_prod.TBGPRODHL2DESC,
            ibp_prod.TBGPRODHL3DESC,
            ibp_prod.TBGPRODHL4DESC,
            ibp_prod.TBGPRODHL5DESC,
            concat(ibp_prod.TBGPRODHL3DESC," ",ibp_prod.TBGPRODHL5DESC) as IBP_SubBrandVolumeSize,
            LPAD(PROD_ID,18,'0') AS IBP_MATERIAL,
            dim_cust.CUSTOMERNAME1,
            dim_cust.CUSTOMERNAME2,
            dim_cust.CUSTOMERNAME3,
            dim_cust.CUSTOMERNAME4,
            dim_cust.CUSTOMERNAME5
            FROM uc_prod.dw_s_ibp.s_am_ibp_shipments_forecast_uc ibp
            LEFT JOIN uc_prod.dw_s_ibp.s_cv_dim_ibp_prdid ibp_prod
            ON ibp.PROD_ID = ibp_prod.PRDID 
            LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_customer dim_cust
            ON dim_cust.CUSTOMER = ibp.CUST_ID

            WHERE 
            1=1
            AND dim_cust.SALES_ORGANIZATION = 'US12'
            AND ibp.PERIOD_ID LIKE "%25-%"
            -- TESTING
            -- AND dim_cust.CUSTOMERNAME5 = 'WAKEFERN FOODS'
            -- AND ibp_prod.TBGPRODHL3DESC = 'KEVITA SPD'
            -- AND dim_cust.CUSTOMERNAME1 = 'NORTH AMERICA'
            -- AND dim_cust.CUSTOMERNAME2 <> 'CANADA'


            GROUP BY ALL
    )
,
dim_cust AS(
  SELECT 
  DISTINCT
  CUSTOMERNAME1,
  CUSTOMERNAME2,
  CUSTOMERNAME3,
  CUSTOMERNAME4,
  CUSTOMERNAME5,
  HKUNNR5
  FROM uc_prod.dw_s_md.s_mdm_cv_dim_customer
),
tpm AS(
  SELECT
    *,
    LPAD(MATERIAL,18,'0') AS SAP_MATERIAL,
    CASE
      WHEN F_SPDTDESC = 'OI %' THEN BIC_ATP_OI
      WHEN F_SPDTDESC = 'BB Direct %' THEN BIC_ATP_BB
      WHEN F_SPDTDESC = 'BB Indirect %' THEN BIC_ATP_BBIN
      WHEN F_SPDTDESC = 'Scan %' THEN BIC_ATT_SCAN
      WHEN F_SPDTDESC = 'Depletion %' THEN BIC_ATP_DPN
    END AS ALLOWANCE_PCT,
    -- BIC_ATP_OI + BIC_ATP_BB + BIC_ATP_BBIN + BIC_ATT_SCAN + BIC_ATP_DPN AS ALLOWANCE_PCT,
    CASE
      WHEN F_SPDTDESC = 'OI Rate/Case' THEN BIC_ATT_OI
      WHEN F_SPDTDESC = 'BB Direct Rate/Case' THEN BIC_ATT_BB
      WHEN F_SPDTDESC = 'BB Ind. Rate/Case' THEN BIC_ATT_BBIN
      WHEN F_SPDTDESC = 'Scan Rate/Case' THEN BIC_ATC_SCAN
      WHEN F_SPDTDESC = 'Depletion Rate/Case' THEN BIC_ATT_DPN
    END AS ALLOWANCE_CASE,    
    -- BIC_ATT_OI + BIC_ATT_BB + BIC_ATT_BBIN + BIC_ATC_SCAN + BIC_ATT_DPN AS ALLOWANCE_CASE,
    CASE
      WHEN F_SPDTDESC = 'BB Direct %' THEN BIC_ATA_BBP
      WHEN F_SPDTDESC = 'BB Direct Rate/Case' THEN BIC_ATA_BBC
      WHEN F_SPDTDESC = 'BB Indirect %' THEN BIC_ATA_BB_0 -- + BIC_ATA_BBIN
      WHEN F_SPDTDESC = 'BB Ind. Rate/Case' THEN BIC_ATA_BBIN -- CONFIRM second option BIC_ATL_EDLP
      WHEN F_SPDTDESC = 'Coupon Fixed' THEN BIC_ATL_CPN --CONFIRM
      WHEN F_SPDTDESC = 'Depletion %' THEN BIC_ATA_DPNP
      WHEN F_SPDTDESC = 'Depletion Rate/Case' THEN BIC_ATA_DPNC
      WHEN F_SPDTDESC = 'Display Fixed' THEN BIC_ATL_DSP  --CONFIRM
      WHEN F_SPDTDESC = 'Feature Fixed' THEN BIC_ATL_FTR2 --CONFIRM BIC_ATL_FTR is for Lump Sum
      WHEN F_SPDTDESC = 'Fixed' THEN BIC_ATL_SHLF --CONFIRM
      WHEN F_SPDTDESC = 'OI %' THEN BIC_ATA_OIP
      WHEN F_SPDTDESC = 'OI Rate/Case' THEN BIC_ATA_OIC
      WHEN F_SPDTDESC = 'Scan %' THEN BIC_ATA_SCNP
      WHEN F_SPDTDESC = 'Scan Rate/Case' THEN BIC_ATA_SCNC
      WHEN F_SPDTDESC = 'Slotting Fixed' THEN BIC_ATL_SLT  --CONFIRM
    END AS FORECAST_TRADE_SPEND
    -- BIC_ATA_SCNP + BIC_ATL_EDLP+BIC_ATL_FTR + BIC_ATL_DSP + BIC_ATL_CPN + BIC_ATL_FTR2 + BIC_ATL_SHLF + BIC_ATL_SLT + BIC_ATA_DPNC + BIC_ATA_DPNP AS FORECAST_TRADE_SPEND
  FROM uc_prod.dw_s_tpm.s_tbg_am_tpm_tmacpr012
  WHERE 1=1
  AND SALESORG = 'US12'
  AND CALYEAR = '2025'
--   AND `/BIC/APRMSTD` NOT IN ('Committed')
--   AND CALWEEK IN ('202521','202522','202523','202524')
)
-- SELECT * FROM tpm WHERE 
-- 1=1 
-- -- AND CRM_MKTELM IN ('T-00039855','T-00042349','T-00042352','T-00042354') 
-- AND CRM_MKTELM IN ('T-00039589')
-- AND CALWEEK = '202522'
,

TPM_AGG AS (
SELECT 
-- tpm.*,
tpm.SAP_MATERIAL,
tpm.CRM_MKTELM as T_CODE,
CALWEEK,
FISCPER_NO,
CALYEAR,
F_SPDTDESC as SPEND_TYPE,
OBJECTIVE_DE as TERM,
`/BIC/APRMSTD` AS STATUS,
MAX(BIC_ANT_LSTP) as LIST_PRICE,
MAX(ALLOWANCE_PCT) as ALLOWANCE_PCT,
MAX(ALLOWANCE_CASE) as ALLOWANCE_CASE,
SUM(`/BIC/AVT_SCAN`) as SCAN_VOLUME,
SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
SUM(`/BIC/APA_TGSSH`) as FORECAST_GROSS_DOLLARS,
SUM(`/BIC/AVT_BASSH`) as FORECAST_TOTAL_SHIPMENT_VOLUME,
MAX(`/BIC/APA_TOTRD`) AS T_CODE_TRADE_SPEND,
dim_cust.CUSTOMERNAME1,
dim_cust.CUSTOMERNAME2,
dim_cust.CUSTOMERNAME3,
dim_cust.CUSTOMERNAME4,
dim_cust.CUSTOMERNAME5,
tpm.L6_CUST_TEXT,
dim_prod.PRODUCTHIERARCHY_L1_TEXT,
dim_prod.PRODUCTHIERARCHY_L2_TEXT,
dim_prod.PRODUCTHIERARCHY_L3_TEXT,
dim_prod.PRODUCTHIERARCHY_L4_TEXT,
dim_prod.PRODUCTHIERARCHY_L5_TEXT,
concat(dim_prod.PRODUCTHIERARCHY_L3_TEXT," ",dim_prod.PRODUCTHIERARCHY_L5_TEXT) as TPM_SubBrandVolumeSize
FROM tpm
LEFT JOIN dim_cust
ON tpm.CUST_SALES = dim_cust.HKUNNR5
LEFT JOIN uc_prod.dw_s_md.s_mdm_cv_dim_product dim_prod
ON tpm.SAP_MATERIAL = dim_prod.PRODUCT
WHERE
1=1
AND tpm.CRM_MKTELM != " "
-- AND F_SPDTDESC in ('BB Direct %')
-- AND tpm.CRM_MKTELM = 'T-00048903'
-- 'T-00025639'
GROUP BY ALL
-- HAVING SUM(FORECAST_TRADE_SPEND) >0
-- ORDER BY TPM_SubBrandVolumeSize,SPEND_TYPE,CALWEEK
)

-- SELECT 
--   *
--   -- DISTINCT CUSTOMERNAME2, CUSTOMERNAME3, CUSTOMERNAME4, CUSTOMERNAME5, L6_CUST_TEXT
-- FROM TPM_AGG
-- WHERE CUSTOMERNAME5 = "BOG USA EDLC OI" 
-- -- WHERE
-- L6_CUST_TEXT <>" "
-- ORDER BY 1,2,3,4,5
-- CUSTOMERNAME5 LIKE 'WAKEFERN%'
-- -- AND TPM_SubBrandVolumeSize = 'NAKED JUICE SMOOTHIE 15.2 OZ'
-- AND FISCPER_NO = '6'
,


IBP2TPM AS(
SELECT 
TPM_AGG.T_CODE,
TPM_AGG.STATUS,
COALESCE(TPM_AGG.CALWEEK,IBP6.IBP_CALWEEK,IBP5.IBP_CALWEEK) as CALWEEK,
TPM_AGG.FISCPER_NO,
COALESCE(LEFT(TPM_AGG.CALWEEK,4),LEFT(IBP6.IBP_CALWEEK,4),LEFT(IBP5.IBP_CALWEEK,4)) AS CALYEAR,
TPM_AGG.SPEND_TYPE,
TPM_AGG.TERM,
-- TPM_AGG.STATUS,
TPM_AGG.LIST_PRICE,
TPM_AGG.ALLOWANCE_PCT,
TPM_AGG.ALLOWANCE_CASE,
TPM_AGG.SCAN_VOLUME,
TPM_AGG.FORECAST_TRADE_SPEND,
TPM_AGG.FORECAST_GROSS_DOLLARS,
TPM_AGG.FORECAST_TOTAL_SHIPMENT_VOLUME,
TPM_AGG.T_CODE_TRADE_SPEND,
COALESCE(TPM_AGG.CUSTOMERNAME1,IBP6.CUSTOMERNAME1,IBP5.CUSTOMERNAME1) as CUSTOMERNAME1, 
COALESCE(TPM_AGG.CUSTOMERNAME2,IBP6.CUSTOMERNAME2,IBP5.CUSTOMERNAME2) as CUSTOMERNAME2,
COALESCE(TPM_AGG.CUSTOMERNAME3,IBP6.CUSTOMERNAME3,IBP5.CUSTOMERNAME3) as CUSTOMERNAME3,
COALESCE(TPM_AGG.CUSTOMERNAME4,IBP6.CUSTOMERNAME4,IBP5.CUSTOMERNAME4) as CUSTOMERNAME4,
COALESCE(TPM_AGG.CUSTOMERNAME5,IBP6.CUSTOMERNAME5,IBP5.CUSTOMERNAME5) as CUSTOMERNAME5,
COALESCE(TPM_AGG.L6_CUST_TEXT,IBP6.CUSTOMERNAME6) as CUSTOMERNAME6,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L1_TEXT,IBP6.TBGPRODHL1DESC,IBP5.TBGPRODHL1DESC) as PRODUCTHIERARCHY_L1_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L2_TEXT,IBP6.TBGPRODHL2DESC,IBP5.TBGPRODHL2DESC) as PRODUCTHIERARCHY_L2_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L3_TEXT,IBP6.TBGPRODHL3DESC,IBP5.TBGPRODHL3DESC) as PRODUCTHIERARCHY_L3_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L4_TEXT,IBP6.TBGPRODHL4DESC,IBP5.TBGPRODHL4DESC) as PRODUCTHIERARCHY_L4_TEXT,
COALESCE(TPM_AGG.PRODUCTHIERARCHY_L5_TEXT,IBP6.TBGPRODHL5DESC,IBP5.TBGPRODHL5DESC) as PRODUCTHIERARCHY_L5_TEXT,
COALESCE(TPM_AGG.TPM_SubBrandVolumeSize,IBP6.IBP_SubBrandVolumeSize,IBP5.IBP_SubBrandVolumeSize) as SubBrandVolumeSize,
COALESCE(TPM_AGG.SAP_MATERIAL,IBP6.IBP_MATERIAL,IBP5.IBP_MATERIAL) AS MATERIAL,
IBP6.IBP_DEMAND_PLAN AS IBP_DEMAND_PLAN_L6,
IBP5.IBP_DEMAND_PLAN,
CASE
    WHEN COALESCE(IBP6.IBP_DEMAND_PLAN,IBP5.IBP_DEMAND_PLAN) <=0 THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN COALESCE(IBP6.IBP_DEMAND_PLAN,IBP5.IBP_DEMAND_PLAN) IS NULL THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN RIGHT(TPM_AGG.SPEND_TYPE,5) = 'Fixed' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SCAN_VOLUME > IBP6.IBP_DEMAND_PLAN AND LEFT(TPM_AGG.SPEND_TYPE,4)='Scan' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct %','Depletion %','OI %','Scan %') THEN TPM_AGG.ALLOWANCE_PCT*TPM_AGG.LIST_PRICE*IBP6.IBP_DEMAND_PLAN/100
    WHEN TPM_AGG.L6_CUST_TEXT != ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct Rate/Case','Depletion Rate/Case','OI Rate/Case','Scan Rate/Case') THEN TPM_AGG.ALLOWANCE_CASE*IBP6.IBP_DEMAND_PLAN

    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SCAN_VOLUME > IBP5.IBP_DEMAND_PLAN AND LEFT(TPM_AGG.SPEND_TYPE,4)='Scan' THEN TPM_AGG.FORECAST_TRADE_SPEND
    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct %','Depletion %','OI %','Scan %') THEN TPM_AGG.ALLOWANCE_PCT*TPM_AGG.LIST_PRICE*IBP5.IBP_DEMAND_PLAN/100
    WHEN TPM_AGG.L6_CUST_TEXT = ' ' AND TPM_AGG.SPEND_TYPE IN ('BB Direct Rate/Case','Depletion Rate/Case','OI Rate/Case','Scan Rate/Case') THEN TPM_AGG.ALLOWANCE_CASE*IBP5.IBP_DEMAND_PLAN
    -- FIGURE OUT THE INDIRECT SPENDS 'BB Indirect %','BB Ind. Rate/Case',
END AS CALCULATED_TRADE_SPEND
FROM TPM_AGG
FULL OUTER JOIN IBP6
ON 
    TPM_AGG.SAP_MATERIAL = IBP6.IBP_MATERIAL
    AND TPM_AGG.L6_CUST_TEXT = IBP6.CUSTOMERNAME6
    AND TPM_AGG.CALWEEK = IBP6.IBP_CALWEEK
-- WHERE IBP.PERIOD_ID LIKE "P06%"
FULL OUTER JOIN IBP5
ON 
    TPM_AGG.SAP_MATERIAL = IBP5.IBP_MATERIAL
    AND TPM_AGG.CUSTOMERNAME5 = IBP5.CUSTOMERNAME5
    AND TPM_AGG.CALWEEK = IBP5.IBP_CALWEEK
-- WHERE IBP.PERIOD_ID LIKE "P06%"
ORDER BY TPM_AGG.CUSTOMERNAME5, TPM_AGG.T_CODE, TPM_AGG.TPM_SubBrandVolumeSize, TPM_AGG.SPEND_TYPE, TPM_AGG.CALWEEK
)

SELECT * FROM IBP2TPM
WHERE FISCPER_NO in ('8','9','10')

-- ,

-- IBP2TPM_AGG0 AS(
-- SELECT
-- CUSTOMERNAME1,
-- CUSTOMERNAME2,
-- CUSTOMERNAME3,
-- CUSTOMERNAME4,
-- CUSTOMERNAME5,
-- CUSTOMERNAME6,
-- PRODUCTHIERARCHY_L1_TEXT,
-- PRODUCTHIERARCHY_L2_TEXT,
-- PRODUCTHIERARCHY_L3_TEXT,
-- PRODUCTHIERARCHY_L4_TEXT,
-- PRODUCTHIERARCHY_L5_TEXT,
-- SubBrandVolumeSize,
-- MATERIAL,
-- -- T_CODE,
-- CALWEEK,
-- CONCAT(CALYEAR,LPAD(COALESCE(FISCPER_NO,INT((CAST(CALWEEK as Numeric)-202497)/4)),2,'0')) AS SAC_Period,
-- COALESCE(FISCPER_NO,INT((CAST(CALWEEK as Numeric)-202497)/4)) AS FISCPER_NO,
-- CALYEAR,
-- -- TERM,
-- -- STATUS,
-- MAX(LIST_PRICE) as LIST_PRICE,
-- SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
-- MAX(FORECAST_GROSS_DOLLARS) as FORECAST_GROSS_DOLLARS,
-- MAX(FORECAST_TOTAL_SHIPMENT_VOLUME) as FORECAST_TOTAL_SHIPMENT_VOLUME,
-- MAX(IBP_DEMAND_PLAN_L6) AS IBP_DEMAND_PLAN_L6,
-- MAX(IBP_DEMAND_PLAN) as IBP_DEMAND_PLAN,
-- -- MAX(T_CODE_TRADE_SPEND) AS T_CODE_TRADE_SPEND,
-- COALESCE(SUM(CALCULATED_TRADE_SPEND),0) AS CALCULATED_TRADE_SPEND
-- -- MAX(LIST_PRICE)*MAX(IBP_DEMAND_PLAN) AS CALCULATED_GROSS_DOLLARS,

-- FROM IBP2TPM
-- GROUP BY ALL),


-- IBP2TPM_AGG1 AS(
-- SELECT
-- CUSTOMERNAME1,
-- CUSTOMERNAME2,
-- CUSTOMERNAME3,
-- CUSTOMERNAME4,
-- CUSTOMERNAME5,
-- CUSTOMERNAME6,
-- PRODUCTHIERARCHY_L1_TEXT,
-- PRODUCTHIERARCHY_L2_TEXT,
-- PRODUCTHIERARCHY_L3_TEXT,
-- PRODUCTHIERARCHY_L4_TEXT,
-- PRODUCTHIERARCHY_L5_TEXT,
-- SubBrandVolumeSize,
-- -- MATERIAL,
-- -- T_CODE,
-- CALWEEK,
-- SAC_Period,
-- FISCPER_NO,
-- CALYEAR,
-- -- TERM,
-- -- STATUS,
-- MAX(LIST_PRICE) as LIST_PRICE,
-- SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
-- SUM(FORECAST_GROSS_DOLLARS) as FORECAST_GROSS_DOLLARS,
-- SUM(FORECAST_TOTAL_SHIPMENT_VOLUME) as FORECAST_TOTAL_SHIPMENT_VOLUME,
-- SUM(IBP_DEMAND_PLAN_L6) AS IBP_DEMAND_PLAN_L6,
-- SUM(IBP_DEMAND_PLAN) as IBP_DEMAND_PLAN,
-- -- MAX(T_CODE_TRADE_SPEND) AS T_CODE_TRADE_SPEND,
-- COALESCE(SUM(CALCULATED_TRADE_SPEND),0) AS CALCULATED_TRADE_SPEND
-- -- MAX(LIST_PRICE)*MAX(IBP_DEMAND_PLAN) AS CALCULATED_GROSS_DOLLARS,

-- FROM IBP2TPM_AGG0
-- GROUP BY ALL

-- ),

-- IBP2TPM_AGG2 AS (
--   SELECT
-- CUSTOMERNAME1,
-- CUSTOMERNAME2,
-- CUSTOMERNAME3,
-- CUSTOMERNAME4,
-- CUSTOMERNAME5,
-- CUSTOMERNAME6,
-- PRODUCTHIERARCHY_L1_TEXT,
-- PRODUCTHIERARCHY_L2_TEXT,
-- PRODUCTHIERARCHY_L3_TEXT,
-- PRODUCTHIERARCHY_L4_TEXT,
-- PRODUCTHIERARCHY_L5_TEXT,
-- SubBrandVolumeSize,
-- -- T_CODE,
-- -- CALWEEK,
-- SAC_Period,
-- FISCPER_NO,
-- CALYEAR,
-- -- TERM,
-- -- STATUS,
-- MAX(LIST_PRICE) as LIST_PRICE,
-- SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
-- SUM(FORECAST_GROSS_DOLLARS) as FORECAST_GROSS_DOLLARS,
-- SUM(FORECAST_TOTAL_SHIPMENT_VOLUME) as FORECAST_TOTAL_SHIPMENT_VOLUME,
-- SUM(IBP_DEMAND_PLAN_L6) as IBP_DEMAND_PLAN_L6,
-- SUM(IBP_DEMAND_PLAN) as IBP_DEMAND_PLAN,
-- -- MAX(T_CODE_TRADE_SPEND) AS T_CODE_TRADE_SPEND,
-- SUM(CALCULATED_TRADE_SPEND) AS CALCULATED_TRADE_SPEND
-- -- MAX(LIST_PRICE)*MAX(IBP_DEMAND_PLAN) AS CALCULATED_GROSS_DOLLARS,

-- FROM IBP2TPM_AGG1
-- GROUP BY ALL
-- ),

-- IBP2TPM_AGG3 AS (
--   SELECT
-- CUSTOMERNAME1,
-- CUSTOMERNAME2,
-- CUSTOMERNAME3,
-- CUSTOMERNAME4,
-- CUSTOMERNAME5,
-- -- CUSTOMERNAME6,
-- PRODUCTHIERARCHY_L1_TEXT,
-- PRODUCTHIERARCHY_L2_TEXT,
-- PRODUCTHIERARCHY_L3_TEXT,
-- PRODUCTHIERARCHY_L4_TEXT,
-- PRODUCTHIERARCHY_L5_TEXT,
-- SubBrandVolumeSize,
-- -- T_CODE,
-- -- CALWEEK,
-- SAC_Period,
-- FISCPER_NO,
-- CALYEAR,
-- -- TERM,
-- -- STATUS,
-- MAX(LIST_PRICE) as LIST_PRICE,
-- SUM(FORECAST_TRADE_SPEND) as FORECAST_TRADE_SPEND,
-- SUM(FORECAST_GROSS_DOLLARS) as FORECAST_GROSS_DOLLARS,
-- SUM(FORECAST_TOTAL_SHIPMENT_VOLUME) as FORECAST_TOTAL_SHIPMENT_VOLUME,
-- SUM(IBP_DEMAND_PLAN_L6) as IBP_DEMAND_PLAN_L6,
-- MAX(IBP_DEMAND_PLAN) as IBP_DEMAND_PLAN,
-- -- MAX(T_CODE_TRADE_SPEND) AS T_CODE_TRADE_SPEND,
-- SUM(CALCULATED_TRADE_SPEND) AS CALCULATED_TRADE_SPEND
-- -- MAX(LIST_PRICE)*MAX(IBP_DEMAND_PLAN) AS CALCULATED_GROSS_DOLLARS,

-- FROM IBP2TPM_AGG2
-- GROUP BY ALL
-- )


-- SELECT 

-- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME1,SAC_DIM.CUSTOMERNAME1) AS CUSTOMERNAME1,
-- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME2,SAC_DIM.CUSTOMERNAME2) AS CUSTOMERNAME2,
-- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME3,SAC_DIM.CUSTOMERNAME3) AS CUSTOMERNAME3,
-- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME4,SAC_DIM.CUSTOMERNAME4) AS CUSTOMERNAME4,
-- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME5,SAC_DIM.CUSTOMERNAME5) AS CUSTOMERNAME5,
-- -- COALESCE(IBP2TPM_AGG.CUSTOMERNAME6,SAC_DIM.CUSTOMERNAME6) AS CUSTOMERNAME6,
-- COALESCE(IBP2TPM_AGG3.PRODUCTHIERARCHY_L1_TEXT,SAC_DIM.PRODUCTHIERARCHY_L1_TEXT) AS PRODUCTHIERARCHY_L1_TEXT,
-- COALESCE(IBP2TPM_AGG3.PRODUCTHIERARCHY_L2_TEXT,SAC_DIM.PRODUCTHIERARCHY_L2_TEXT) AS PRODUCTHIERARCHY_L2_TEXT,
-- COALESCE(IBP2TPM_AGG3.PRODUCTHIERARCHY_L3_TEXT,SAC_DIM.PRODUCTHIERARCHY_L3_TEXT) AS PRODUCTHIERARCHY_L3_TEXT,
-- COALESCE(IBP2TPM_AGG3.PRODUCTHIERARCHY_L4_TEXT,SAC_DIM.PRODUCTHIERARCHY_L4_TEXT) AS PRODUCTHIERARCHY_L4_TEXT,
-- COALESCE(IBP2TPM_AGG3.PRODUCTHIERARCHY_L5_TEXT,SAC_DIM.PRODUCTHIERARCHY_L5_TEXT) AS PRODUCTHIERARCHY_L5_TEXT,
-- COALESCE(IBP2TPM_AGG3.SubBrandVolumeSize,SAC_DIM.SubBrandVolumeSize) AS SubBrandVolumeSize,
-- COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) as SAC_Period,
-- COALESCE(IBP2TPM_AGG3.FISCPER_NO,INT((CAST(SAC_DIM.Date as Numeric)-202497)/4)) AS FISCPER_NO,
-- COALESCE(IBP2TPM_AGG3.CALYEAR,LEFT(SAC_DIM.Date,4)) AS CALYEAR,
-- IBP2TPM_AGG3.LIST_PRICE,
-- IBP2TPM_AGG3.FORECAST_TRADE_SPEND,
-- IBP2TPM_AGG3.FORECAST_GROSS_DOLLARS,
-- IBP2TPM_AGG3.FORECAST_TOTAL_SHIPMENT_VOLUME,
--   IBP2TPM_AGG3.IBP_DEMAND_PLAN,
--   SAC_DIM.SHIPPED_CS_SAC,
--   SAC_DIM.GROSS_SALES_SAC,
--   SAC_DIM.TRADE_SPEND_SAC,
--   SAC_DIM.SHIPPED_CS_AOP,
--   SAC_DIM.GROSS_SALES_AOP,
--   SAC_DIM.TRADE_SPEND_AOP,
--   SAC_PRICING_BOY.LIST_PRICE_BOY5,
--   SAC_PRICING_BOY4.LIST_PRICE_BOY4,
--   CASE
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) >= var_period THEN IBP_DEMAND_PLAN
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) < var_period THEN SHIPPED_CS_SAC
--   END AS SHIPMENTS_COMPILED,
--   CASE
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) >= var_period THEN CALCULATED_TRADE_SPEND
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) < var_period THEN SAC_DIM.TRADE_SPEND_SAC
--   END AS TRADE_SPEND_COMPILED,
--   CASE
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) >= var_period THEN COALESCE(SAC_PRICING_BOY.LIST_PRICE_BOY5,SAC_PRICING_BOY4.LIST_PRICE_BOY4,LIST_PRICE)*COALESCE(IBP_DEMAND_PLAN,FORECAST_TOTAL_SHIPMENT_VOLUME)
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) < var_period THEN SAC_DIM.GROSS_SALES_SAC
--   END AS GROSS_SALES_COMPILED,
--   CASE
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) >= var_period THEN "BOY"
--     WHEN COALESCE(IBP2TPM_AGG3.SAC_Period,SAC_DIM.Date) < var_period THEN "YTD"
--   END AS YTD_BOY

-- FROM IBP2TPM_AGG3
-- FULL OUTER JOIN SAC_DIM
-- ON 
--   IBP2TPM_AGG3.SubBrandVolumeSize = SAC_DIM.SubBrandVolumeSize
--   AND IBP2TPM_AGG3.CUSTOMERNAME5 = SAC_DIM.CUSTOMERNAME5
--   AND IBP2TPM_AGG3.SAC_Period = SAC_DIM.Date
-- LEFT JOIN SAC_PRICING_BOY
-- ON 
--   IBP2TPM_AGG3.SubBrandVolumeSize = SAC_PRICING_BOY.SubBrandVolumeSize
--   AND IBP2TPM_AGG3.CUSTOMERNAME5 = SAC_PRICING_BOY.CUSTOMERNAME5

-- LEFT JOIN SAC_PRICING_BOY4
-- ON 
--   IBP2TPM_AGG3.SubBrandVolumeSize = SAC_PRICING_BOY4.SubBrandVolumeSize
--   AND IBP2TPM_AGG3.CUSTOMERNAME4 = SAC_PRICING_BOY4.CUSTOMERNAME4

-- WHERE 1=1
--   -- COALESCE(IBP2TPM_AGG3.CUSTOMERNAME3,SAC_DIM.CUSTOMERNAME3) = 'METRO NY' 
-- ORDER BY SAC_Period,CUSTOMERNAME5, SubBrandVolumeSize

